apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Change the namespace to the namespace you want to deploy the resources
namespace: mattermost

resources:
- mattermost
- php-ldap-client/Kubernetes

configurations:
- namespace.yaml

images:
- name: mamo-ldap-php-client
  newName: mannapperuma/mamo-ldap-php-client
  newTag: v1.0.0-alpine-fpm-8.3.4
- name: nginx-image
  newName: nginx
  newTag: 1.25.4-bookworm

