apiVersion: v1
kind: Service
metadata:
  name: php-ldap-client-service
  namespace: mattermost-operator
spec:
  selector:
    app: php-ldap-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
