apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: mattermost-team-edition
  repo: https://helm.mattermost.com
  releaseName: mattermost
  version: 6.6.51
  includeCRDs: true
  skipTests: true
  valuesFile: values.yaml

secretGenerator:
- name: postgres-connection-string
  type: Opaque
  envs:
  - "configs/postgres/postgres-connection.env"
  options:
    disableNameSuffixHash: true

configMapGenerator:
- name: mattermost-custom-config
  envs:
  - "configs/mattermost/configs.env"
  options:
    disableNameSuffixHash: true
