fullnameOverride: mattermost
nameOverride: mattermost

mysql:
  enabled: false

externalDB:
  enabled: true

service:
  type: NodePort

extraInitContainers:
- command:
  - sh
  - '-c'
  - chown -R 2000:2000 /client/plugins
  image: busybox
  name: changeowner-plugins
  volumeMounts:
  - mountPath: /client/plugins
    name: mattermost-plugins
- command:
  - sh
  - '-c'
  - chown -R 2000:2000 /data
  image: busybox
  name: changeowner-data
  volumeMounts:
  - mountPath: /data
    name: mattermost-data
## Additional env vars
extraEnvVars:
- name: MM_GITLABSETTINGS_ID
  valueFrom:
    secretKeyRef:
      key: CLIENT_ID
      name: ldap-secrets
- name: MM_GITLABSETTINGS_SECRET
  valueFrom:
    secretKeyRef:
      key: CLIENT_SECRET
      name: ldap-secrets
- name: MM_GITLABSETTINGS_BUTTONTEXT
  value: Google Sign In
- name: MM_SQLSETTINGS_DATASOURCE
  valueFrom:
    secretKeyRef:
      key: DB_CONNECTION_STRING
      name: postgres-connection-string
- name: MM_SERVICESETTINGS_SITEURL
  valueFrom:
    configMapKeyRef:
      key: HOST_URL
      name: mattermost-custom-config
- name: MM_FILESETTINGS_AMAZONS3ACCESSKEYID
  valueFrom:
    secretKeyRef:
      key: accesskey
      name: mb-mattermost-iam-access-key
- name: MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY
  valueFrom:
    secretKeyRef:
      key: secretkey
      name: mb-mattermost-iam-access-key
- name: MM_FILESETTINGS_DRIVERNAME
  value: amazons3
- name: MM_FILESETTINGS_AMAZONS3BUCKET
  value: dev-mb-mattermost
- name: MM_FILESETTINGS_AMAZONS3ENDPOINT
  value: storage.googleapis.com
- name: MM_FILESETTINGS_AMAZONS3SSL
  value: "true"
- name: MM_PLUGINSETTINGS_ENABLEUPLOADS
  value: "true"
- name: MM_METRICSSETTINGS_ENABLE
  value: "true"
- name: MM_METRICSSETTINGS_LISTENADDRESS
  value: :8067
- name: MM_CLUSTERSETTINGS_ENABLE
  value: "false"
- name: MM_CLUSTERSETTINGS_CLUSTERNAME
  value: production
- name: MM_FILESETTINGS_MAXFILESIZE
  value: "1048576000"
- name: MM_FILESETTINGS_AMAZONS3SSE
  value: "true"
- name: MM_TEAMSETTINGS_RESTRICTCREATIONTODOMAINS
  value: <Your Domain which users are located>
- name: MM_EMAILSETTINGS_ENABLESIGNINWITHEMAIL
  value: "false"
- name: MM_EMAILSETTINGS_ENABLESIGNINWITHUSERNAME
  value: "false"
- name: MM_TEAMSETTINGS_ENABLECUSTOMBRAND
  value: "true"
- name: MM_TEAMSETTINGS_CUSTOMBRANDTEXT
  value: <Branding Text>
config:
  MM_PLUGINSETTINGS_CLIENTDIRECTORY: "./client/plugins"
  MM_GITLABSETTINGS_ENABLE: 'true'
  MM_SQLSETTINGS_DRIVERNAME: 'postgres'
  MM_GITLABSETTINGS_AUTHENDPOINT: 'https://<mattermost-host-name>/oauth/authorize'
  MM_GITLABSETTINGS_TOKENENDPOINT: 'https://<mattermost-host-name>/oauth/token.php'
  MM_GITLABSETTINGS_USERAPIENDPOINT: 'https://<mattermost-host-name>/oauth/resource.php'

